"""empty message

Revision ID: 581550eea09b
Revises: 
Create Date: 2020-12-01 06:23:37.226919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581550eea09b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_first_name'), 'employees', ['first_name'], unique=False)
    op.create_index(op.f('ix_employees_last_name'), 'employees', ['last_name'], unique=False)
    op.create_index(op.f('ix_employees_username'), 'employees', ['username'], unique=True)
    op.create_table('vehicle_vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_name', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('address', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('city', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('state', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('zip', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('stock_number', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('vin', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('year', sa.String(length=4, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('make', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('model', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('series', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('vehicle_body', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('trim', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('new_used', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('cpo', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('photos', sa.String(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('description', sa.String(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('engine', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('transmission', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('drive', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('fuel', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('options', sa.String(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('image_date', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('vehicle_type', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('tag_line', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('color_exterior', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('color_interior', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('brakes', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('seats', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('warranty', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('vehicle_condition', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('price_retail', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('price_internet', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('price_wholesale', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('price_book_retail', sa.String(length=255, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('data_tier', sa.SmallInteger(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('photo_count', sa.Integer(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin')
    )
    op.create_index(op.f('ix_vehicle_vehicle_account_id'), 'vehicle_vehicle', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_vehicle_account_id'), table_name='vehicle_vehicle')
    op.drop_table('vehicle_vehicle')
    op.drop_index(op.f('ix_employees_username'), table_name='employees')
    op.drop_index(op.f('ix_employees_last_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_first_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    op.drop_table('roles')
    op.drop_table('departments')
    # ### end Alembic commands ###
